/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.tela;

/**
 *
 * @author pc
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraTela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtCapturaLogin = new javax.swing.JTextField();
        TxtCapturaEmail = new javax.swing.JTextField();
        TxtCapturaNomeCompleto = new javax.swing.JTextField();
        TxtCapturaSenha = new javax.swing.JPasswordField();
        BotaoLogar = new javax.swing.JButton();
        MarcarDesenvolvedores = new javax.swing.JCheckBox();
        MarcarScrummaster = new javax.swing.JCheckBox();
        MarcarTestador = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        usuarioControl = new javax.swing.JMenu();
        projetoControl = new javax.swing.JMenu();
        outrasControl = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Cadastro");
        setResizable(false);

        jLabel1.setText("Login");

        jLabel2.setText("Senha");

        jLabel3.setText("Email");

        jLabel4.setText("Nome Completo");

        TxtCapturaLogin.setText("Digite seu Login");
        TxtCapturaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCapturaLoginActionPerformed(evt);
            }
        });

        TxtCapturaEmail.setText("Digite Seu E-mail");
        TxtCapturaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCapturaEmailActionPerformed(evt);
            }
        });

        TxtCapturaNomeCompleto.setText("Digite Seu Nome");

        TxtCapturaSenha.setText("jPasswordField1");
        TxtCapturaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCapturaSenhaActionPerformed(evt);
            }
        });

        BotaoLogar.setText("Logar Usuário");
        BotaoLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLogarActionPerformed(evt);
            }
        });

        MarcarDesenvolvedores.setText("Desenvolvedores");

        MarcarScrummaster.setText("ScrumMaster");
        MarcarScrummaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcarScrummasterActionPerformed(evt);
            }
        });

        MarcarTestador.setText("Testador");
        MarcarTestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcarTestadorActionPerformed(evt);
            }
        });

        usuarioControl.setText("Usuários");
        jMenuBar1.add(usuarioControl);

        projetoControl.setText("Projetos");
        jMenuBar1.add(projetoControl);

        outrasControl.setText("Outras Opções");
        jMenuBar1.add(outrasControl);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(TxtCapturaNomeCompleto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtCapturaEmail)
                            .addComponent(TxtCapturaLogin)
                            .addComponent(TxtCapturaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MarcarTestador)
                            .addComponent(MarcarScrummaster)
                            .addComponent(MarcarDesenvolvedores))
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotaoLogar)
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtCapturaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtCapturaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtCapturaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtCapturaNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MarcarDesenvolvedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MarcarScrummaster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(MarcarTestador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoLogar)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCapturaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCapturaLoginActionPerformed
        
    }//GEN-LAST:event_TxtCapturaLoginActionPerformed

    private void TxtCapturaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCapturaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCapturaSenhaActionPerformed

    private void TxtCapturaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCapturaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCapturaEmailActionPerformed

    private void BotaoLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLogarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoLogarActionPerformed

    private void MarcarScrummasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcarScrummasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcarScrummasterActionPerformed

    private void MarcarTestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcarTestadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcarTestadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoLogar;
    private javax.swing.JCheckBox MarcarDesenvolvedores;
    private javax.swing.JCheckBox MarcarScrummaster;
    private javax.swing.JCheckBox MarcarTestador;
    private javax.swing.JTextField TxtCapturaEmail;
    private javax.swing.JTextField TxtCapturaLogin;
    private javax.swing.JTextField TxtCapturaNomeCompleto;
    private javax.swing.JPasswordField TxtCapturaSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu outrasControl;
    private javax.swing.JMenu projetoControl;
    private javax.swing.JMenu usuarioControl;
    // End of variables declaration//GEN-END:variables
}
